import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt" className="bg-white">
      <body className="bg-white text-black min-h-screen flex flex-col">
        <Header />
        <main className="flex-1 px-12">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
